---
- name: Despliegue de aplicacion ToDo
  hosts: centos
  become: true
  user: sysadmin

  tasks:

    - name: Instalar JDK de java
      ansible.builtin.dnf: 
        name: java-11-openjdk-devel
        state: present

    - name: Instalar Podman
      ansible.builtin.dnf:
        name: podman
        state: present

    - name: Crear grupo Tomcat si no existe
      ansible.builtin.group:
        name: tomcat
        state: present

    - name: Crear usuario Tomcat si no existe
      ansible.builtin.user:
        name: tomcat
        comment: "Tomcat User"
        home: /opt/tomcat
        shell: /bin/nologin
        group: tomcat
        state: present
   
    - name: Asignar permisos correctos al directorio de Tomcat
      ansible.builtin.command:
        cmd: chown -R tomcat:tomcat /opt/tomcat

    - name: Crear directorio para Tomcat
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Crear directorio para clonar el repositorio
      ansible.builtin.file:
        path: /tomcat
        state: directory

    - name: Descargar Apache Tomcat
      ansible.builtin.get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz
        dest: /opt/tomcat

    - name: Extraer Apache Tomcat
      ansible.builtin.unarchive:
        src: /opt/tomcat/apache-tomcat-9.0.91.tar.gz
        dest: /opt/tomcat
        remote_src: yes

    - name: Asignar permisos correctos al directorio de Tomcat
      ansible.builtin.command:
        cmd: chown -R tomcat:tomcat /opt/tomcat
    
    - name: Configurar Tomcat como servicio           ### Prompt de chatgpt como configurar tomcat como servicio
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk"
          Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
          ExecStart=/opt/tomcat/apache-tomcat-9.0.91/bin/startup.sh
          ExecStop=/opt/tomcat/apache-tomcat-9.0.91/bin/shutdown.sh
          SuccessExitStatus=143
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Recargar demonio systemd
      command: systemctl daemon-reload
    
    - name: Habilitar y arrancar servicio Tomcat
      ansible.builtin.systemd:
        name: tomcat
        enabled: yes
        state: started

    - name: Clonar aplicación
      ansible.builtin.git:
        repo: "https://github.com/eoriguela/Tomcat-Todo.git"
        dest: /tomcat

    - name: Desplegar aplicación ToDo
      ansible.builtin.copy:
        src: /tomcat/todo.war
        dest: /opt/tomcat/webapps/

    - name: Habilitar puertos en el Firewall
      ansible.posix.firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled

    - name: Recargar Firewall
      ansible.builtin.command:
        cmd: firewall-cmd --reload
