---
- name: Configuro servidor base de datos en ubuntu
    hosts: database
    become: true
  user: sysadmin

  
  tasks:

- name: UFW Instalado
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Habilitar puerto 22 en ufw
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Defino politicas de trafico Saliente
  community.general.ufw:
    policy: allow
    direction: outgoing
    state: enabled

- name: Defino politicas de trafico Entrante
  community.general.ufw:
    policy: allow
    direction: incoming
    state: enabled


- name: UFW Servicio UP y Active
  ansible.builtin.systemd_service:
    name: ufw
    state: started
    enabled: true


### Instalación de base de datos
    
- name: MariaDB Instalado
  ansible.builin.apt:
      name: mariadb-server
      state: present
      update-cache: true

- name: Servidor Mariadb levantado
  ansible.builtin.systemd_service:
      name: mariadb
      state: started
      enabled: true
  
- name: Habilitamos en ufw la conexión a mariadb
  community.general.ufw:
      rule: allow
      port: "3306"
      protocol: tcp
      direction: in 

### Configuración de la base de datos
- name: Creamos la base de datos todo
  community.mysql.mysql_db:
      check_implicit_admin: true
      login_host: "{{ hostvars[inventory_hostname].ansible.host }}"
      login_user: root
      login_password: dbadmin
      name: todo
      state: present
      target: ./files/todo.sql
  delegate_to: localhost
  connection: local


